增加翻译：账户继任者相关
maboloshi/github-chinese pull request #214
Opened 2024-07-02 14:48 UTC by qznfbnj

账户设置 - 设置继任者
== 用户邀请翻译 无效 单独放便于处理（需要测试随时提出）
== F12表示：请注意对应 page false 词库节点不存在 参见 #213 
顺便修改一处原翻译的句式

2024-07-02 14:58 UTC, TC999 commented
"114514"

2024-07-02 15:11 UTC, maboloshi commented
@qznfbnj F12下 运行, 把结果发上来😊
```
const isLogin = document.body.classList.contains("logged-in");
const analyticsLocation = document.head.querySelector('meta[name="analytics-location"]')?.content || '';
const isOrganization = /\/<org-login>/.test(analyticsLocation) || /^\/(?:orgs|organizations)/.test(location.pathname);
const isRepository = /\/<user-name>\/<repo-name>/.test(analyticsLocation);
const isProfile = document.body.classList.contains("page-profile") || analyticsLocation === '/<user-name>';
const isSession = document.body.classList.contains("session-authentication");
console.log(`${isLogin},${analyticsLocation},${isOrganization},${isRepository},${isProfile},${isSession}`)
```

2024-07-02 15:11 UTC, wuyuncheng-26 commented
「114514」

2024-07-02 15:15 UTC, qznfbnj commented
> @qznfbnj F12下 运行, 把结果发上来😊
> 
> ```
> const isLogin = document.body.classList.contains("logged-in");
> const analyticsLocation = document.head.querySelector('meta[name="analytics-location"]')?.content || '';
> const isOrganization = /\/<org-login>/.test(analyticsLocation) || /^\/(?:orgs|organizations)/.test(location.pathname);
> const isRepository = /\/<user-name>\/<repo-name>/.test(analyticsLocation);
> const isProfile = document.body.classList.contains("page-profile") || analyticsLocation === '/<user-name>';
> const isSession = document.body.classList.contains("session-authentication");
> console.log(`${isLogin},${analyticsLocation},${isOrganization},${isRepository},${isProfile},${isSession}`)
> ```

这样？
![image](https://github.com/maboloshi/github-chinese/assets/100760086/368d5488-8147-4542-b02b-73b28886bef6)
```
true,,false,false,false,false
undefined
```

2024-07-02 15:23 UTC, maboloshi commented
> 
> ```
> true,,false,false,false,false
> undefined
> ```

OK 后期设置`rePagePath`规则应该能识别. 明天吧
![0F10C139](https://github.com/maboloshi/github-chinese/assets/7850715/a50b92ea-f49e-4759-88a7-9865077107d3)

2024-07-02 15:25 UTC, maboloshi commented
`^\/users\/[^\/]+\/(projects|packages)`-->`^\/users\/[^\/]+\/(projects|packages|succession\/invitation)` 试下

2024-07-02 15:29 UTC, qznfbnj commented
不错
![image](https://github.com/maboloshi/github-chinese/assets/100760086/113f1962-7e9e-4467-b8cb-9d18205779cd)

2024-07-02 15:36 UTC, maboloshi requested changes

2024-07-02 15:36 UTC, maboloshi commented on locals.js
> +        [/By clicking \"Add Successor\" below, I acknowledge that I am the owner of the([^@]+@[^\n]+) account, and am authorizing GitHub to transfer content within that account to my GitHub Successor
`在我死亡的情况`😒 这翻译不好

2024-07-02 15:38 UTC, maboloshi commented
对了，翻译引擎除了`chatgpt`外，优先使用`DeepL`

2024-07-02 15:48 UTC, qznfbnj commented
> 对了，翻译引擎除了`chatgpt`外，优先使用`DeepL`

我一般用翻译引擎也是习惯用于预处理 ~~更多还是靠自己不到六级的水平硬翻~~
对了，`I18N.zh["succession/invitation"]` 是否要移动位置？

2024-07-02 15:48 UTC, qznfbnj commented on locals.js
> +        [/By clicking \"Add Successor\" below, I acknowledge that I am the owner of the([^@]+@[^\n]+) account, and am authorizing GitHub to transfer content within that account to my GitHub Successor
总不能是 ~~`我的死亡事件会触发向我的 GitHub 继任者的内容转移`~~ 吧（
`在我死后`？`在我去世后`？

2024-07-03 01:14 UTC, maboloshi commented
> > 对了，翻译引擎除了`chatgpt`外，优先使用`DeepL`
> 
> 我一般用翻译引擎也是习惯用于预处理 ~更多还是靠自己不到六级的水平硬翻~ 对了，`I18N.zh["succession/invitation"]` 是否要移动位置？

目前, 暂时先发到`["settings/admin"]`之下吧

2024-07-03 15:24 UTC, wuyuncheng-26 commented on locals.js
> +        [/By clicking \"Add Successor\" below, I acknowledge that I am the owner of the([^@]+@[^\n]+) account, and am authorizing GitHub to transfer content within that account to my GitHub Successor
这方面用词就要委婉一点，别那么直接（

2024-07-03 15:30 UTC, qznfbnj commented on locals.js
> +        [/By clicking \"Add Successor\" below, I acknowledge that I am the owner of the([^@]+@[^\n]+) account, and am authorizing GitHub to transfer content within that account to my GitHub Successor
嗯，明天有空翻翻历史看谁翻译的

2024-07-03 15:38 UTC, wuyuncheng-26 commented on locals.js
> +        [/By clicking \"Add Successor\" below, I acknowledge that I am the owner of the([^@]+@[^\n]+) account, and am authorizing GitHub to transfer content within that account to my GitHub Successor
翻译成 「过世」 咋样（

2024-07-04 10:54 UTC, maboloshi requested changes

2024-07-04 10:54 UTC, maboloshi commented on locals.js
> +            //"Account security": "账户安全",  // 疑似失效
```suggestion
```

2024-07-04 10:54 UTC, maboloshi commented on locals.js
> +        [/By clicking \"Add Successor\" below, I acknowledge that I am the owner of the([^@]+@[^\n]+) account, and am authorizing GitHub to transfer content within that account to my GitHub Successor
```suggestion
        [/By clicking \"Add Successor\" below, I acknowledge that I am the owner of the([^@]+@[^\n]+) account, and am authorizing GitHub to transfer content within that account to my GitHub Successor,/, "通过点击下面的 “添加继任者”，我确认我是 $1 账户的所有者，并授权 GitHub 将此账户内的内容转让给我的 GitHub 继任者"],
```

2024-07-04 10:54 UTC, maboloshi commented on locals.js
> +        [/By clicking \"Add Successor\" below, I acknowledge that I am the owner of the([^@]+@[^\n]+) account, and am authorizing GitHub to transfer content within that account to my GitHub Successor
原文没这意思就不翻译了

2024-07-04 10:54 UTC, maboloshi commented on locals.js
> +        [/By clicking \"Add Successor\" below, I acknowledge that I am the owner of the([^@]+@[^\n]+) account, and am authorizing GitHub to transfer content within that account to my GitHub Successor
用`承认`好，还是`确认`好？

2024-07-04 10:54 UTC, maboloshi commented on locals.js
> -            ", in the event of my death. I understand that this appointment of a successor does not override legally binding next-of-kin rules or estate laws of any relevant jurisdiction, and does no
不翻译此处的`，在我死亡的情况下。`也不无不妥，大家怎么看

2024-07-04 11:00 UTC, maboloshi requested changes

2024-07-04 11:00 UTC, maboloshi commented on locals.js
> +            //"Account security": "账户安全",  // 疑似失效
```suggestion
```
确实失效删除

2024-07-04 11:05 UTC, merged