修复标题等被误翻译的问题
maboloshi/github-chinese pull request #239
Opened 2024-07-11 02:45 UTC by TC999

修复议题：#215，#236，#238

解决方法：
`and`词条前后加空格

2024-07-11 02:57 UTC, maboloshi commented
补一个示例链接

2024-07-11 03:06 UTC, TC999 commented
@maboloshi 发行版示例页面:[BewlyBewly](https://github.com/BewlyBewly/BewlyBewly/releases)

2024-07-11 05:07 UTC, maboloshi commented
@TC999
`反应为` 翻译貌似有点生硬，以下仅示例
```
        [/([^ ]+) reacted with thumbs up emoji/, "$1 点赞"],
        [/([^ ]+) reacted with laugh emoji/, "$1 表示微笑"],
        [/([^ ]+) reacted with hooray emoji/, "$1 欢呼"],
        [/([^ ]+) reacted with heart emoji/, "$1 比了个心"],
        [/([^ ]+) reacted with rocket emoji/, "$1 发送小火箭"],
        [/([^ ]+) reacted with eyes emoji/, "$1 表示关注"],
        [/(\d+) (people|person) reacted/, "$1 位伙伴表达看法"],
```

2024-07-11 08:31 UTC, maboloshi commented
另外 `某个讨论页面`也有`反应`功能

2024-07-11 08:34 UTC, wuyuncheng-26 commented
得本土化翻译（
想起来之前搜索界面还有一个 `GitHub 一下，你就知道`
有一次被我删了（bushi）

2024-07-11 08:38 UTC, wuyuncheng-26 commented
> @TC999 `反应为` 翻译貌似有点生硬，以下仅示例
> 
> ```
>         [/([^ ]+) reacted with thumbs up emoji/, "$1 点赞"],
>         [/([^ ]+) reacted with laugh emoji/, "$1 表示微笑"],
>         [/([^ ]+) reacted with hooray emoji/, "$1 欢呼"],
>         [/([^ ]+) reacted with heart emoji/, "$1 比了个心"],
>         [/([^ ]+) reacted with rocket emoji/, "$1 发送小火箭"],
>         [/([^ ]+) reacted with eyes emoji/, "$1 表示关注"],
>         [/(\d+) (people|person) reacted/, "$1 位伙伴表达看法"],
> ```
这挺好的

2024-07-11 08:52 UTC, wuyuncheng-26 commented
```
        [/([^ ]+) reacted with thumbs up emoji/, "$1 点了个赞"],
        [/([^ ]+) reacted with laugh emoji/, "$1 表示微笑"],
        [/([^ ]+) reacted with hooray emoji/, "$1 欢呼了"],
        [/([^ ]+) reacted with heart emoji/, "$1 比了个心"],
        [/([^ ]+) reacted with rocket emoji/, "$1 发送了小火箭"],
        [/([^ ]+) reacted with eyes emoji/, "$1 表示关注"],
        [/(\d+) (people|person) reacted/, "$1 位伙伴表达了看法"],
```

2024-07-11 08:57 UTC, maboloshi commented
> 欢呼了

`表示微笑`->`微微一笑`
`欢呼了`->`欢呼一下`
`表示关注`->`see see 一下`

怎么样 😊

2024-07-11 09:03 UTC, TC999 commented
议题、拉取请求页面也有

2024-07-11 09:05 UTC, maboloshi commented
我以前不翻译是觉得 不是很重要 因为需要添加不少正则规则

2024-07-11 09:09 UTC, TC999 commented
`点踩`
`表示疑惑`

2024-07-11 12:27 UTC, wuyuncheng-26 commented
直接加进 public 吧

2024-07-11 12:28 UTC, maboloshi commented
> 直接加进 public 吧

没必要加重正则负担

2024-07-11 14:13 UTC, TC999 commented
加到仓库公共部分就行了，仪表板页面的有些区别

2024-07-11 14:15 UTC, TC999 commented
议题、拉取请求、讨论、发行版页面，用户名都是逐个列出，太多就列几个后用数字
仪表板页面全是数字

2024-07-11 14:43 UTC, maboloshi commented
目前，不考虑将相关正则添加到`repository-public`

2024-07-11 15:01 UTC, TC999 commented
那就把词条复制几份分别移到几个页面下

2024-07-11 15:08 UTC, TC999 commented
@maboloshi 刚把仓库公共部分的更改全删了，分散到其他页面

2024-07-11 15:10 UTC, maboloshi commented
我明天看一下

2024-07-12 03:20 UTC, maboloshi commented
[提交页面](https://github.com/maboloshi/github-chinese/pull/239/commits/7d44e06fc200a7055b235b138a0a3bf894c2bace) 这个提交，请创建新分支吧

2024-07-12 03:20 UTC, maboloshi commented
这个PR 解决相关`反应`问题

2024-07-15 03:50 UTC, maboloshi requested changes

2024-07-15 03:50 UTC, maboloshi commented on locals.js
> +
```suggestion
```

这部分由 #242 处理

2024-07-15 03:50 UTC, maboloshi commented on locals.js
> +                "This comment was marked as resolved.": "该评论被标记为已解决。",
这部分由 https://github.com/maboloshi/github-chinese/pull/242 处理

2024-07-29 08:13 UTC, maboloshi submitted a review, later dismissed

2024-07-29 08:15 UTC, maboloshi commented
奇怪 为啥还冲突呢🤔。算了 等有心情再来补

2024-07-29 09:45 UTC, maboloshi commented
@TC999 你这边能本地解决一下冲突么

2024-07-29 12:31 UTC, TC999 commented
> @TC999 你这边能本地解决一下冲突么

我这边看不到哪里冲突

2024-07-29 12:34 UTC, maboloshi commented
算了, 我在考虑要不要使用函数的方式 使用一条规则搞定

2024-07-29 13:56 UTC, maboloshi commented
你最后的2个提交应该是提交到`TC999/dev`把 然后在重新 PR 的把

2024-07-29 13:59 UTC, TC999 commented
……本地仓库是`dev`，本地仓库切分支比较麻烦
或者发下冲突位置，我去解决

2024-07-29 14:36 UTC, maboloshi commented
> ……本地仓库是`dev`，本地仓库切分支比较麻烦 或者发下冲突位置，我去解决

到时我新开 PR好了

2024-07-29 14:36 UTC, closed without merging

2024-07-29 14:42 UTC, maboloshi commented
明天继续调试
```js
        [/^([^, ]+(?:, [^, ]+,)*)(?: and (\d+) more| and ([^,]+))? reacted with (\w+) emoji$/, function (all, usernames, moreCount, lastUsername, emojiText) {
            const emoji = {
                'thumbs up': '点了个赞',
                'thumbs down': '点了个赞', //讨论
                laugh: '微微一笑',
                hooray: '欢呼一下',
                heart: '比了个心',
                rocket: '发送了小火箭',
                eyes: 'see 一下',
                confused: '有点困惑',
            };
            return usernames + (moreCount ? '和另外 ' + moreCount + ' 个人' : lastUsername ? ' 和 ' + lastUsername : '' ) + ' ' + emoji[emojiText];
        }],
```
正则还是不太对

2024-08-10 14:46 UTC, TC999 commented
压缩规则https://github.com/maboloshi/github-chinese/pull/263/commits/d48218ea2dfa28bb2ed9c93ccacf326a293721e8