在 locals.js 中更新汉化翻译
maboloshi/github-chinese pull request #249
Opened 2024-07-24 11:04 UTC by KS-OTO

- 有关代码空间、预构建的文案汉化，涉及个人设置、仓库设置；
- 有关个人设置的邮箱设置、通知设置的补充汉化；
- 有关仓库主页、议题的细节优化；
- 有关GitHub个人主页-feed流的细节优化；

涉及：https://github.com/KS-OTO/github-chinese/issues/1 ， https://github.com/KS-OTO/github-chinese/issues/2 ， https://github.com/KS-OTO/github-chinese/issues/3 ， https://github.com/KS-OTO/github-chinese/issues/5 ， https://github.com/KS-OTO/github-chinese/issues/6 ， https://github.com/KS-OTO/github-chinese/issues/7 ， https://github.com/KS-OTO/github-chinese/issues/9 ， https://github.com/KS-OTO/github-chinese/issues/11

2024-07-24 11:28 UTC, wuyuncheng-26 approved these changes

2024-07-24 11:31 UTC, wuyuncheng-26 commented
粗略看了看，应该是没什么问题的
现在在火车上，到家再细致看看 :)

2024-07-24 11:57 UTC, wuyuncheng-26 commented
下次请去设置一下 GPG 签名，否则无法正常合并
教程见 https://docs.github.com/zh/authentication/managing-commit-signature-verification

2024-07-24 14:12 UTC, wuyuncheng-26 submitted a review, later dismissed

2024-07-24 14:13 UTC, wuyuncheng-26 commented
@maboloshi 您那边可以强制合并吗

2024-07-24 15:07 UTC, maboloshi commented
还有一些翻译，还没时间校对。 再放放吧

2024-07-25 07:01 UTC, wuyuncheng-26 commented on locals.js
> +                    "🚀 My stack": "技术栈",
个人感觉这个并不需要翻译

2024-07-25 07:15 UTC, KS-OTO commented on locals.js
> +                    "🚀 My stack": "技术栈",
我是出于“能译尽译”的原则。既然咱们这个汉化插件是想帮助英语小白能更好的使用和掌握GitHub这个软件，那么一方面是尽可能的将页面说明类、引导类、功能类文字进行汉化，同时也可以将一些系统缺省/预设值的内容一并进行汉化，以引导小白用户能够轻松理解这块的设计意图，也能在减少认知的负担的同时，为其使用该功能提供一些助益。

2024-07-25 07:16 UTC, wuyuncheng-26 commented on locals.js
> +                    "🚀 My stack": "技术栈",
hmmm 那也许应该加上表情（

2024-07-25 07:25 UTC, KS-OTO commented on locals.js
> +                    "🚀 My stack": "技术栈",
好的，我会在后续提交时补充

2024-07-25 09:50 UTC, maboloshi requested changes

2024-07-25 09:50 UTC, maboloshi commented on locals.js
> +            "This email will be used as an additional destination for security-relevant account notifications and can also be used for password resets.": "该电子邮件将用作与账户安全相关通知的额外接收地址，也可用于密码重置。",
```suggestion
            "This email will be used as an additional destination for security-relevant account notifications and can also be used for password resets.": "该电子邮箱将用作与账户安全相关通知的额外接收地址，也可用于密码重置。",
```

2024-07-25 09:50 UTC, maboloshi commented on locals.js
> +            "To stop receiving emails for the topics below, uncheck any topics you don't want to receive, then click Save subscription preferences": "若要停止接收以下主题的电子邮件，请取消选中您不想接收的主题，然后操作保存",
```suggestion
            "To stop receiving emails for the topics below, uncheck any topics you don't want to receive, then click Save subscription preferences": "若要停止接收以下主题的电子邮件，请取消选中您不想接收的主题，然后点击 “保存订阅首选项”",
```

2024-07-25 10:16 UTC, KS-OTO commented on locals.js
> +            "This email will be used as an additional destination for security-relevant account notifications and can also be used for password resets.": "该电子邮件将用作与账户安全相关通知的额外接收地址，也可用于密码重置。",
是的，我没有注意到邮件的错误使用，确实应该是邮箱

2024-07-25 10:17 UTC, KS-OTO commented on locals.js
> +            "To stop receiving emails for the topics below, uncheck any topics you don't want to receive, then click Save subscription preferences": "若要停止接收以下主题的电子邮件，请取消选中您不想接收的主题，然后操作保存",
我是想着顺从用户操作习惯，并简化该内容。

2024-07-25 10:25 UTC, KS-OTO reviewed
完成

2024-07-25 12:22 UTC, wuyuncheng-26 submitted a review, later dismissed

2024-07-26 02:11 UTC, maboloshi commented
@KS-OTO 你这种方式挺好的。相关翻译最近我抽时间在斟酌一下👍

2024-07-31 01:50 UTC, maboloshi requested changes

2024-07-31 01:50 UTC, maboloshi commented on locals.js
> +        "Security &amp; analysis": "代码安全性与分析",
```suggestion
        "Security & analysis": "安全性与分析",
```

2024-07-31 01:50 UTC, maboloshi commented on locals.js
```suggestion
            "The email in this signature doesn’t match the committer email.": "此签名中的电子邮箱与提交者的电子邮箱不相符。",
            "No user is associated with the committer email.": "没有用户与提交者的的电子邮箱关联。",

2024-07-31 01:50 UTC, maboloshi commented on locals.js
> +            "Update profile settings ": "更新个人资料设置",
```suggestion
            "Only you can see your full profile.": "只有您可以查看完整的个人资料。",
            "You have marked your profile as private, which limits what activity other people can see. ": "您已将个人资料设为私密，这会限制其他人看到您的活动。",
            "View what others see": "以他人视角查看",
            "View full profile": "查看完整个人资料",
            "Update profile settings": "更新个人资料设置",
```

2024-07-31 05:43 UTC, maboloshi requested changes

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +                "Choose where you'd like emails to be sent. You can add more email addresses. Use custom routes to specify different email addresses to be used for individual organizations.": "请选择您默认
```suggestion
                "Choose where you'd like emails to be sent. You can add more email addresses. Use custom routes to specify different email addresses to be used for individual organizations.": "请选择希望接收通知邮件的邮箱。您可以添加多个邮箱地址。可借助自定义路由为不同的组织指定不同的邮箱地址。",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +                    "is your current default email for notifications.": "是您目前默认的通知邮箱",
```suggestion
                    "You can send notifications to different": "您可借助自定义路由为不同的组织指定不同的邮箱地址",
                    "verified": "（经验证的邮箱）",
                    "email addresses depending on the organization that owns the repository.": "。",
                    "is your current default email for notifications.": "是您目前默认的通知邮箱。",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +                    "is your current default email for notifications.": "是您目前默认的通知邮箱",
精简了表述

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +            "This email will be used as an additional destination for security-relevant account notifications and can also be used for password resets.": "该电子邮箱将用作与账户安全相关通知的额外接收地址，也可用于密码重置。",
```suggestion
                "At least one non-backup email is required.": "至少需要一个非备用电子邮箱",
            "Backup": "备用电子邮箱",
            "This email will be used as an additional destination for security-relevant account notifications and can also be used for password resets.": "该电子邮箱将用作接收账户安全相关通知的额外方式，也可以用于密码重置。",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +            "No user is associated with the committer email.": "此签名中的电子邮箱在账号设置中不存在",
```suggestion
            "The email in this signature doesn’t match the committer email.": "此签名中的电子邮箱与提交者的电子邮箱不相符。",
            "No user is associated with the committer email.": "提交者的电子邮箱未与用户相关联。",

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +                    "You’re receiving notifications because you were assigned.": "因您是该议题的受理人，为此你将接收该议题的最新通知",
```suggestion
```

将该词条移步到`I18N.zh["repository/pull_issue_public"]`的`You’re receiving notifications because`附近？
另外，翻译调整为：
```
您收到通知是因为您受理了它。
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +                "Codespaces Prebuilds": "预构建代码空间",
```suggestion

            "Codespaces Prebuilds": "代码空间预构建",
                "Showing all prebuild configuration runs for Codespaces. Learn about": "显示代码空间所有预构建设置的运行情况。了解",
                "prebuilding your codespaces.": "代码空间预构建。",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +            "See output": "查看结果",
```suggestion

            // 状态
                "Currently Running": "正在运行中",
                "Disabled": "禁用",

            "See output": "查看输出结果",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +            "prebuild configuration.": "预构建的设置",
```suggestion
            "prebuild configuration.": "预构建设置。",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
>          // 代码空间 /<user-name>/<repo-name>/settings/codespaces
```suggestion
        // 代码空间-新建预构建设置 /<user-name>/<repo-name>/settings/codespaces/prebuild_configurations/new
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +            "prebuild configurations": "了解代码空间预构建的计费",
```suggestion
            // 黄色警告
                "Prebuilds consume storage space that will incur a billable charge. Learn more about": 预构建会占用存储空间，可能会产生费用。了解更多关于",
                "prebuild configurations": "预构建设置",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +                "By default, your prebuilt image will be available to all regions where codespaces are available and storage costs will apply for each region. You can adjust this to manage your stora
```suggestion
            "Reduce prebuild availability to only specific regions": "仅在特定地区提供预构建",
                "By default, your prebuilt image will be available to all regions where codespaces are available and storage costs will apply for each region. You can adjust this to manage your storage usage.": "默认情况下，您的预构建镜像将在所有提供代码空间的地区可用，并且每个地区都会产生存储费用。您可以对此进行调整，以管理存储空间的使用。",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +            "Disabled": "禁用",
```suggestion
            "Configuration menu": "设置菜单",
                "Manually trigger": "手动触发",
                "View runs": "查看运行日志",
                "Disable runs":"暂停运行",
                "Enable runs":"恢复运行",
                
            // 删除对话框
                "Are you sure?": "您确定吗？",
                "Are you sure you want to delete this prebuild configuration? Running workflow may fail and templates associated with this configuration will be deleted.": "您确定要删除这个预构建设置吗？运行中的工作流可能会失败，与此设置相关的模板将被删除。",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +            "Prebuild configuration": "预构建设置",
```suggestion
            // 顶部提醒
                "Prebuild configuration created": "预构建设置已创建",
                "Prebuild configuration deleted": "预构建设置已删除",

            "Prebuild configuration": "预构建设置",
```

2024-07-31 05:43 UTC, maboloshi commented on locals.js
> +            "Development environment secrets are environment variables that are encrypted. They are available to any codespace you create using repositories with access to that secret.": "代码空间机密是被加密的
```suggestion
            "Development environment secrets are environment variables that are encrypted. They are available to any codespace you create using repositories with access to that secret.": "开发环境机密是加密的环境变量。它们可用于您可访问该机密的仓库创建的任何代码空间。",
```

2024-07-31 09:39 UTC, maboloshi requested changes

2024-07-31 09:39 UTC, maboloshi commented on locals.js
> +                    "Notifications for the conversations you are participating in, or if someone cites you with an @mention. Also for all activity when subscribed to specific events.": "当您参与的对话有新的通知、
```suggestion
                    "Notifications for the conversations you are participating in, or if someone cites you with an @mention. Also for all activity when subscribed to specific events.": "参与的对话、或有人 @您、以及您订阅的特定事件所发出的通知。",
```

2024-07-31 09:39 UTC, maboloshi commented on locals.js
> +                    "to add emoji to the name or description.": "可在名称或描述中添加表情符号",
```suggestion
                    // 小贴士
                        "type : to add emoji to the name or description.": "输入: 在名称或描述中添加表情符号", 
```

2024-07-31 09:39 UTC, maboloshi commented on locals.js
> +                    "Notifications for all repositories, teams, or conversations you're watching.": "当您关注的仓库、团队或对话有新的变化时您将收到通知。",
```suggestion
                    "Notifications for all repositories, teams, or conversations you're watching.": "所有您关注的仓库、团队或对话所发出的通知。",
```

2024-07-31 09:49 UTC, merged