增加词条：零散词条补充
maboloshi/github-chinese pull request #263
Opened 2024-08-09 05:44 UTC by TC999

大致更改：账单页、首页、操作页、仓库设置页

2024-08-09 08:01 UTC, maboloshi submitted a review, later dismissed

2024-08-09 08:01 UTC, maboloshi commented on locals.js
> +        "Search...": "搜索…",
```suggestion
        "Search...": "搜索...",
```

2024-08-09 08:01 UTC, maboloshi commented on locals.js
> +        "Help": "帮助",
```suggestion
            "Signed in as": "登录身份为",
            "Your gists": "我的代码片段",
            "Starred gists": "我的标星代码片段",
            "Help": "帮助",
```

2024-08-09 08:01 UTC, maboloshi commented on locals.js
有劳调整一下位置，并帮我加一下
![image](https://github.com/user-attachments/assets/2179850d-ccd0-45bf-ae83-4a600a19605d)

```
            // 搜索框
                "Search:": "搜索：",
                "(Use /re/ syntax for regexp search)": "（使用 /re/ 语法进行正则搜索）",
        "Attach files by selecting or pasting them.": "通过选择或粘贴来附加文件。",
            // 底部栏
                "Use": "使用",
                "to toggle the": "切换",
                "key moving focus.": "键移动对焦。",
```

2024-08-09 08:01 UTC, maboloshi commented on locals.js
gist中的` // 分享工具条`如下调整

```
        // 分享工具条
        "What would you like to do?": "您想做什么？",
        "Embed": "嵌入",
            "Embed this gist in your website.": "嵌入到您的网页中。",
        "Share": "分享",
            "Copy sharable link for this gist.": "复制片段共享链接。",
        "Clone via HTTPS": "通过 HTTPS 方式克隆",
            "Clone using the web URL.": "使用 Web URL 克隆。",
        "Clone via SSH": "通过 SSH 方式克隆",
            "Clone with an SSH key and passphrase from your GitHub settings.": "通过 GitHub 设置中的 SSH 密钥和密码进行克隆。",
        "Learn more about clone URLs": "了解更多关于克隆地址的信息",
```

2024-08-09 08:01 UTC, maboloshi commented on locals.js
还有这个
![image](https://github.com/user-attachments/assets/feef20b1-271c-4a34-9d21-ac2945ffa102)

```
        "Unstar": "取消星标",
            "Unstar this gist": "取消该代码片段星标",
        "Forks": "复刻",
            "Fork this gist": "复刻代码片段",
        "User actions": "用户操作",
        "Report abuse": "举报滥用",

        "Code": "代码",
        "Revisions": "修订",
        "Stars": "星标",
        // "Forks": "复刻",
```

2024-08-09 08:01 UTC, maboloshi commented on locals.js
![image](https://github.com/user-attachments/assets/cd032666-98a4-41a4-80c9-6e35cbd88c05)
```
        // 返回通知页状态条
            "Back to notifications": "回到通知",
            "Done": "已完成",
            "Unsubscribe": "退订",
            "Mark as unread": "标记为未读",
            "Save": "保存",
```

2024-08-09 08:19 UTC, TC999 commented on locals.js
> +        "Search...": "搜索…",
这个非常离谱，未登录和已登录后面的标点还不一样

2024-08-09 08:30 UTC, TC999 commented
@maboloshi 加完了，您来看下

2024-08-11 01:25 UTC, wuyuncheng-26 requested changes

2024-08-11 01:25 UTC, wuyuncheng-26 commented on locals.js
> +                    "DNS check unsuccessful": "DNS 检查不成功",
这翻译成失败会不会好一点……
```suggestion
                    "DNS check unsuccessful": "DNS 检查失败",
```

2024-08-11 02:28 UTC, wuyuncheng-26 commented
才意识到一直以来代码里的 `public` 都拼错了🤣

2024-08-11 02:28 UTC, wuyuncheng-26 approved these changes

2024-08-11 02:41 UTC, wuyuncheng-26 approved these changes

2024-08-11 02:50 UTC, wuyuncheng-26 commented
你搞完了通知我一声（

2024-08-11 02:53 UTC, TC999 commented
@wuyuncheng-26 搞完了

2024-08-11 03:00 UTC, merged

2024-08-11 03:02 UTC, wuyuncheng-26 commented
艹，报错了

2024-08-11 03:07 UTC, wuyuncheng-26 commented
搞错了搞错了
现在可以了