增加词条：零散词条补充
maboloshi/github-chinese pull request #266
Opened 2024-08-12 08:28 UTC by TC999

大致更改：赞助页、账户设置、仓库安全设置

2024-08-12 09:49 UTC, maboloshi requested changes

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +                "Show more workflows...": "显示更多…",
```suggestion
                "Show more workflows...": "显示更多...",
```

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +            "Code review limits are currently": "目前,所有仓库都",
```suggestion
            "Code review limits are currently": "目前，所有仓库都",
```

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +            "for all repositories. All users are able to submit pull request reviews, including those that \"approve\" or \"request changes\". Limit reviews to only permit users who have explicitly b
```suggestion
            "for all repositories. All users are able to submit pull request reviews, including those that \"approve\" or \"request changes\". Limit reviews to only permit users who have explicitly been granted access to each repository to submit reviews that \"approve\" or \"request changes\".": "代码审查限制。所有用户都可以提交拉取请求审查，包括那些 “批准” 或 “请求更改” 的审查 。限制审查，只允许明确授予每个仓库访问权的用户提交 “批准” 或 “请求更改” 的审查。",
```

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +        [/before transforming ([^ ]+) into an organization./, "。"],
正则出处最好截图一下，另外，这2句必须拆分是吧

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +            // 具体某个信息
补一下截图

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +                    "This alert is not relevant": "该警报无关",
```suggestion
                    "This secret has been revoked": "机密被撤销",
                    "This secret is not in production code": "机密不在生产代码中",
                    "This alert is not valid": "警报无效",
                    "This alert is not relevant": "警报无关",
```
删除了冠词，貌似不影响理解

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +            "These counts are approximate and may not exactly match the dependents shown below.": "这些人数是近似值，可能与下面显示的人数不完全一致。",
```suggestion
            "These counts are approximate and may not exactly match the dependents shown below.": "这些计数是近似值，可能与下方显示的依赖项不完全匹配。",
```

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +                "Invite collaborator": "邀请协作者",
重复了？

2024-08-12 09:49 UTC, maboloshi commented on locals.js
确定不需要缩进是吧

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +                    "Use runners labeled with 'dependency-submission'": "使用带 '依赖提交' 标签的运行程序",
```suggestion
                    "Use runners labeled with 'dependency-submission'": "使用带 “dependency-submission” 标签的运行器",
```
标签名不用翻译

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +                    "No runners with this label assigned to repository": "没有为仓库分配带有此标签的运行程序",
```suggestion
                    "No runners with this label assigned to repository": "没有为仓库分配带有此标签的运行器",
```

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +        "Custom properties allow you to decorate your repository with information such as compliance frameworks, data sensitivity, or project details.": "自定义属性允许您使用合规框架、数据敏感性或项目细节等信息来装饰您的仓库。",
```suggestion
        "Custom properties allow you to decorate your repository with information such as compliance frameworks, data sensitivity, or project details.": "自定义属性允许您为仓库添加信息，例如合规框架、数据敏感性或项目详情。",
```

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +        "No custom properties set for this repository.": "该仓库未设置自定义属性。",
```suggestion
        "No custom properties set for this repository.": "该仓库尚未设置自定义属性。",
```

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +        "Learn more about custom properties": "进一步了解自定义属性",
```suggestion
        "Learn more about custom properties": "了解更多关于自定义属性的信息",
```

2024-08-12 09:49 UTC, maboloshi commented on locals.js
> +        "and how to set them at the organization level.": "以及如何在组织级别设置这些属性。",
```suggestion
        "and how to set them at the organization level.": "以及如何在组织级别进行设置。",
```

2024-08-12 10:07 UTC, maboloshi requested changes

2024-08-12 10:07 UTC, maboloshi commented on locals.js
> +        [/and (\d+) others sponsor this goal/, "和另外 $1 人赞助此目标"],
以上正则出处能否截图

2024-08-12 13:46 UTC, TC999 commented on locals.js
> +        [/before transforming ([^ ]+) into an organization./, "。"],
> 正则出处最好截图一下，另外，这2句必须拆分是吧

<https://github.com/settings/organizations>，左下角“变更 XXX 为组织”按钮

![image](https://github.com/user-attachments/assets/a06c3de0-d293-4f1c-a75b-58552e293e61)

2024-08-12 14:33 UTC, TC999 commented on locals.js
> +            // 具体某个信息
网址为<https://github.com/user/repo/security/secret-scanning/id>

![image](https://github.com/user-attachments/assets/d1296e48-2d25-45df-896c-7ade2d849b73)

2024-08-12 14:34 UTC, TC999 commented on locals.js
> +        [/and (\d+) others sponsor this goal/, "和另外 $1 人赞助此目标"],
赞助者页，示例 <https://github.com/sponsors/chakra-ui>

![image](https://github.com/user-attachments/assets/7dd2675b-9930-46fe-a3e1-c55b6ae942d7)

2024-08-13 02:00 UTC, maboloshi requested changes

2024-08-13 02:00 UTC, maboloshi commented on locals.js
> +                "Reopen alert": "重新打开",
是不是重复了

2024-08-13 02:00 UTC, maboloshi commented on locals.js
> +                "Clear closure reasons": "清除原因",
```suggestion
                "Clear closure reasons": "明确关闭原因",
```

2024-08-13 02:00 UTC, maboloshi commented on locals.js
> +                "Find alerts on your dev dependencies using": "使用以下命令查找开发依赖项的警报：",
提供一下出处截图

2024-08-13 02:00 UTC, maboloshi commented on locals.js
> +        [/([\d,]+) Triages?/, "$1 通知"],
```suggestion
        [/([\d,]+) Triages?/, "$1 分类"],
```

2024-08-13 02:00 UTC, maboloshi commented on locals.js
> +        [/on (.+)/, "$1"],
`[/on (.+)/, "$1"],`重复了

2024-08-13 02:00 UTC, maboloshi commented on locals.js
> +    "static": { // 静态翻
```suggestion
    "static": { // 静态翻译
```

2024-08-13 02:00 UTC, maboloshi commented on locals.js
> +        "You are assigned to this pull request": "您被分配到这个拉取请求",
```suggestion
        "You are assigned to this pull request": "您被指派处理此拉取请求",
```

2024-08-13 02:00 UTC, maboloshi commented on locals.js
> +                "Secret detected": "检测到",
`"Secret detected": "检测到",`也重复了

2024-08-13 02:26 UTC, TC999 commented on locals.js
> +                "Clear closure reasons": "清除原因",
这个是全选

2024-08-13 02:30 UTC, maboloshi requested changes

2024-08-13 02:30 UTC, maboloshi commented on locals.js
> +        [/before transforming ([^ ]+) into an organization./, "。"],
原始英文截个图，看看能不能仅使用一个正则搞定？

2024-08-13 02:31 UTC, TC999 commented on locals.js
> +                "Find alerts on your dev dependencies using": "使用以下命令查找开发依赖项的警报：",
<https://github.com/user/repo/security/dependabot>

![image](https://github.com/user-attachments/assets/697f9452-ec4c-4955-9183-584eac7d951e)

2024-08-13 02:33 UTC, TC999 commented on locals.js
> +        [/before transforming ([^ ]+) into an organization./, "。"],
![image](https://github.com/user-attachments/assets/52457efa-c2ff-48cb-8639-92dcfb43d230)

2024-08-13 05:22 UTC, maboloshi requested changes

2024-08-13 05:22 UTC, maboloshi commented on locals.js
> +                    "View git blame": "浏览 git 追溯",
```suggestion
                    "View git blame": "浏览 Git 追溯",
```

2024-08-13 05:22 UTC, maboloshi commented on locals.js
> +            // 具体某条信息
加个链接模版

2024-08-13 05:22 UTC, maboloshi commented on locals.js
> +            "Select a tier": "选择档位",
```suggestion
            "Select a tier": "选择",
```

2024-08-13 05:22 UTC, maboloshi commented on locals.js
> +                "A Public Sponsor achievement will be added to your profile.": "您的个人档案中将添加公共赞助商成就。",
```suggestion
                "A Public Sponsor achievement will be added to your profile.": "一个 “公开赞助者” 成就将添加到您的个人资料中。",
```

2024-08-13 05:22 UTC, maboloshi commented on locals.js
> +        // 赞助者资料页 https://github.com/sponsors/<user-name>
```suggestion
        // GitHub 赞助者个人资料 https://github.com/sponsors/<user-name>
        // GitHub 赞助者组织资料 https://github.com/sponsors/<org-name>
        // ...?preview=true
            "You are previewing your GitHub Sponsors profile.": "您正在预览您的 GitHub 赞助者个人资料。",
            "Edit your profile.": "编辑您的个人资料。",
            // 组织
            // [/You are previewing ([^ ]+)’s GitHub Sponsors profile./, "您正在预览 $1 组织的 GitHub 赞助者个人资料。"],
            // [/Edit ([^ ]+)’s profile./, "编辑 $1 组织的个人资料。"],
```
![image](https://github.com/user-attachments/assets/d2d7e1d4-6c21-4173-8f2c-7870a33403de)

2024-08-13 05:22 UTC, maboloshi commented on locals.js
> +        // 赞助者资料页 https://github.com/sponsors/<user-name>
另外，在
```
        [/([^ ]+) does not directly depend on any repositories whose maintainers can be sponsored./, "$1 不直接依赖于任何可以赞助其维护人员的仓库。"],
```
之上，添加正则
```
        [/You are previewing ([^ ]+)’s GitHub Sponsors profile./, "您正在预览 $1 组织的 GitHub 赞助者个人资料。"], // sponsors/<org-name>?preview=true
        [/Edit ([^ ]+)’s profile./, "编辑 $1 组织的个人资料。"], // sponsors/<org-name>?preview=true
```

2024-08-13 08:20 UTC, merged