增加词条：零散词条补充
maboloshi/github-chinese pull request #269
Opened 2024-08-16 02:34 UTC by TC999

大致更改：新版仓库洞察贡献者界面#267，搜索页，赞助者页，市场页

2024-08-16 02:36 UTC, wuyuncheng-26 commented
Close #267
________________________________
发件人: ***@***.*** ***@***.***> 代表 陈生杂物房 ***@***.***>
发送时间: 2024年8月15日 19:35
收件人: maboloshi/github-chinese ***@***.***>
抄送: Subscribed ***@***.***>
主题: [maboloshi/github-chinese] 增加词条：零散词条补充 (PR #269)


大致更改：新版仓库洞察贡献者界面#267<https://github.com/maboloshi/github-chinese/issues/267>，搜索页，赞助者页，市场页

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/maboloshi/github-chinese/pull/269

Commit Summary

  *   1469dc3<https://github.com/maboloshi/github-chinese/pull/269/commits/1469dc318b930f72df9b3e744d28cd1bcf4c567f> 114514
  *   cd35d2a<https://github.com/maboloshi/github-chinese/pull/269/commits/cd35d2a08d4e9cf1f64921c669da883f775ed97a> 114514
  *   d1e724c<https://github.com/maboloshi/github-chinese/pull/269/commits/d1e724c3d6edcf623cc544ac6c5088b5785b52d0> 114514
  *   1a6487a<https://github.com/maboloshi/github-chinese/pull/269/commits/1a6487acd8e14a88912ab77ad6532b16a0f4b710> Merge branch 'maboloshi:gh-pages' into gh-pages
  *   d3e49d3<https://github.com/maboloshi/github-chinese/pull/269/commits/d3e49d3d067005232e66c20456fdd36165524366> 114514
  *   746620e<https://github.com/maboloshi/github-chinese/pull/269/commits/746620e34ae3bda80751f55d31069d338e0f037c> Merge branch 'gh-pages' of https://github.com/TC999/github-chinese into gh-pages
  *   d13ddb8<https://github.com/maboloshi/github-chinese/pull/269/commits/d13ddb8130e5e7bc5941b8fd5ed11156b0e1f51b> Merge branch 'maboloshi:gh-pages' into gh-pages
  *   1eeaa9c<https://github.com/maboloshi/github-chinese/pull/269/commits/1eeaa9c9033036ea585d524514db775a0b3aebbc> 新增支持页
  *   9dcde2b<https://github.com/maboloshi/github-chinese/pull/269/commits/9dcde2bf1868b259be8d1202e6a8d542776815b6> 114514
  *   236cc61<https://github.com/maboloshi/github-chinese/pull/269/commits/236cc61458b8bbdae8d94776267ae79f05f36d74> Merge branch 'gh-pages' of https://github.com/TC999/github-chinese into gh-pages
  *   1f9087e<https://github.com/maboloshi/github-chinese/pull/269/commits/1f9087eeb7afc4c27a4999fa4a19560f044156bc> 杂项
  *   db36388<https://github.com/maboloshi/github-chinese/pull/269/commits/db3638893d91c96e185e5e1d04b1aa633b52b415> 删除脚本更改
  *   f732b12<https://github.com/maboloshi/github-chinese/pull/269/commits/f732b12d2f84bfd3b95fd429ebd7cc97f65a5f27> 删除支持页词条
  *   4be831e<https://github.com/maboloshi/github-chinese/pull/269/commits/4be831e27600ea3137ca5362b00f280c8ea3927f> Merge branch 'gh-pages' of https://github.com/TC999/github-chinese into gh-pages
  *   d0a2be4<https://github.com/maboloshi/github-chinese/pull/269/commits/d0a2be4fc4aaf62c98f59582723bd9512588068c> 杂项
  *   6bbe249<https://github.com/maboloshi/github-chinese/pull/269/commits/6bbe249165a9caab7f700d820fe14a964610bd72> 去除多余更改
  *   92898a3<https://github.com/maboloshi/github-chinese/pull/269/commits/92898a36685c8663c9e64923c4f5947839bfa91c> 手动同步
  *   61344b0<https://github.com/maboloshi/github-chinese/pull/269/commits/61344b0d34cbc4dc068887cfe199ce917e2bfc85> Update locals(greasyfork).js
  *   65e9882<https://github.com/maboloshi/github-chinese/pull/269/commits/65e988204b177d25233b4cb7b3590860b4e41056> 手动同步
  *   f9399c2<https://github.com/maboloshi/github-chinese/pull/269/commits/f9399c263e3c9e3b3469d4ee71218bc71e8d9cb3> Merge branch 'gh-pages' of https://github.com/TC999/github-chinese into gh-pages
  *   7993397<https://github.com/maboloshi/github-chinese/pull/269/commits/79933972f50534d59d434d33095801eef076eb1a> Update locals.js
  *   b6b37f3<https://github.com/maboloshi/github-chinese/pull/269/commits/b6b37f3dfe0764da5dabc373ca73e585cdfe9809> Update locals.js
  *   e782316<https://github.com/maboloshi/github-chinese/pull/269/commits/e782316532e003c4e2a0f9ef0a5b3c39a6443b3a> Update locals.js
  *   b80b537<https://github.com/maboloshi/github-chinese/pull/269/commits/b80b53755e36af28597f103067b11520315a3263> Update locals.js
  *   f3c7949<https://github.com/maboloshi/github-chinese/pull/269/commits/f3c79499f4783ab6a63eee0e461e1b8c9314d9a5> 修正
  *   4a9dcc7<https://github.com/maboloshi/github-chinese/pull/269/commits/4a9dcc7f7980dae87eb30a4dd5a83f71b918cb19> Merge branch 'gh-pages' of https://github.com/TC999/github-chinese into gh-pages
  *   f8d25e6<https://github.com/maboloshi/github-chinese/pull/269/commits/f8d25e6261e6d7c93089ff3c624e9ef0d55d55c7> Merge branch 'maboloshi:gh-pages' into gh-pages
  *   41b227b<https://github.com/maboloshi/github-chinese/pull/269/commits/41b227b58c93c2b1f8ca57cca7541331ee5afe2d> 词条改位置
  *   1619ee5<https://github.com/maboloshi/github-chinese/pull/269/commits/1619ee5122a4c0552bc07e9a650dac59dc7af890> 杂项
  *   b82a091<https://github.com/maboloshi/github-chinese/pull/269/commits/b82a0911c39547736538fa9c7380110181fb807e> Merge branch 'gh-pages' of https://github.com/TC999/github-chinese into gh-pages
  *   d17470f<https://github.com/maboloshi/github-chinese/pull/269/commits/d17470f02ed41f25232e43fea5c8d4f62d949e90> 114514
  *   d909feb<https://github.com/maboloshi/github-chinese/pull/269/commits/d909febc9250781b4022616b678bb9ea4e4d1896> Android
  *   4ec572e<https://github.com/maboloshi/github-chinese/pull/269/commits/4ec572e0328ef798cb9094b982100989baef9769> Android UA
  *   c3dcdc1<https://github.com/maboloshi/github-chinese/pull/269/commits/c3dcdc18a6bdb9da4bfde3c86dbdd7fee2faad7a> 杂项
  *   a3c0619<https://github.com/maboloshi/github-chinese/pull/269/commits/a3c06195d80ceba4131838cc75d32b8409289d56> 杂项
  *   257fe99<https://github.com/maboloshi/github-chinese/pull/269/commits/257fe993bb93bdc21639c98f4bf4f87860bace58> Merge branch 'gh-pages' of https://github.com/TC999/github-chinese into gh-pages
  *   213b3bd<https://github.com/maboloshi/github-chinese/pull/269/commits/213b3bd0f6d0e1b9409410e68548f6dad695bbf4> 修正
  *   86f79b1<https://github.com/maboloshi/github-chinese/pull/269/commits/86f79b170b6959060598656aa2930673d0ebb808> Merge branch 'maboloshi:gh-pages' into gh-pages
  *   29648dc<https://github.com/maboloshi/github-chinese/pull/269/commits/29648dc170e92ebe8cd91e06c746b8b0cec88fb7> 杂项
  *   a033a2f<https://github.com/maboloshi/github-chinese/pull/269/commits/a033a2f5f58e6e823bb77a361e4350684fbfa183> Merge branch 'maboloshi:gh-pages' into gh-pages
  *   0594e4f<https://github.com/maboloshi/github-chinese/pull/269/commits/0594e4f6e99093be01eb125e71e8cadd594aa157> 杂项
  *   891f5b9<https://github.com/maboloshi/github-chinese/pull/269/commits/891f5b9e3d21ef5b05a62ba89c5e71179eca4699> 杂项
  *   7ec734e<https://github.com/maboloshi/github-chinese/pull/269/commits/7ec734ebc279f1c6a3aa3e225f6a0d0d2f495d1f> Merge branch 'maboloshi:gh-pages' into gh-pages
  *   98191a2<https://github.com/maboloshi/github-chinese/pull/269/commits/98191a285b38a6f24190110ccc00fa3ed46e329b> 讨论页隐藏评论
  *   10dcd7a<https://github.com/maboloshi/github-chinese/pull/269/commits/10dcd7a353ab1b724ab0d7883ca3ac250e906422> Merge branch 'gh-pages' of https://github.com/TC999/github-chinese into gh-pages
  *   71cb1b2<https://github.com/maboloshi/github-chinese/pull/269/commits/71cb1b263142134f841532051679bd455c3249af> 讨论页`隐藏讨论对话框`
  *   a82413c<https://github.com/maboloshi/github-chinese/pull/269/commits/a82413c3cc25623be0de2550f74a6ded737f7820> 补充: 讨论页`隐藏讨论对话框`
  *   30cb32b<https://github.com/maboloshi/github-chinese/pull/269/commits/30cb32bbf86b436500d1788ea68f86ec89bc9377> Fix 逗号 bug 引入的错误😒
  *   04330db<https://github.com/maboloshi/github-chinese/pull/269/commits/04330db9f58ec521ad94bf6cc5d5e381d49ba7e1> 仓库相关
  *   be7068a<https://github.com/maboloshi/github-chinese/pull/269/commits/be7068a008227c9b8072596db6d0cb5d893ecb69> 搜索页
  *   a167be2<https://github.com/maboloshi/github-chinese/pull/269/commits/a167be2899d60aadafa075c5cfe289a74cd11b4b> Merge branch 'maboloshi:gh-pages' into gh-pages
  *   dc4da85<https://github.com/maboloshi/github-chinese/pull/269/commits/dc4da8557e3963b8a779875d3df2c8c1356c634c> 标题
  *   8528661<https://github.com/maboloshi/github-chinese/pull/269/commits/8528661c00c98d1aca1407a9969f1e05a5255a57> Merge bra [...]

2024-08-16 02:37 UTC, wuyuncheng-26 commented
没事了，我已经加了（

2024-08-16 03:05 UTC, wuyuncheng-26 requested changes

2024-08-16 03:05 UTC, wuyuncheng-26 commented on locals.js
> +                            "Include my email address so I can be contacted": "附上我的电子邮件便于联系",
```suggestion
                            "Include my email address so I can be contacted": "附上我的电子邮件地址以便于联系",
```

2024-08-16 03:39 UTC, maboloshi requested changes

2024-08-16 03:39 UTC, maboloshi commented on locals.js
> +                    "We’re thrilled to introduce our new graphics library! With this update, you’ll find significant enhancements to two of our repository insights views—Contributors and Code Frequen
```suggestion
                    "We’re thrilled to introduce our new graphics library! With this update, you’ll find significant enhancements to two of our repository insights views—Contributors and Code Frequency. Both now utilize an SVG-based solution, offering improved focus navigation for precise, point-by-point interaction. You can also hide a series by interacting with the chart legend and view or download the data in both table format and as PNGs.": "我们非常高兴地介绍我们的新图形库！通过此次更新，您将发现我们的两个仓库洞察视图-- “贡献者” 和 “代码频率” 都有了显著增强。这两个视图现在都采用了基于 SVG 的解决方案，为精确的逐点交互提供了改进的焦点导航。您还可以通过与图表图例交互来隐藏系列，并以表格格式和 PNG 格式查看或下载数据。",
```

2024-08-16 03:39 UTC, maboloshi commented on locals.js
> +        [/This pull request closes issue (#\d+)./, "该拉取请求将关闭议题 $1。"], // 死活不翻译
提供一下 示例我看看

2024-08-16 03:42 UTC, TC999 commented on locals.js
> +        [/This pull request closes issue (#\d+)./, "该拉取请求将关闭议题 $1。"], // 死活不翻译
这个 PR 第一句话里有

2024-08-16 09:33 UTC, TC999 commented on locals.js
> +        [/This pull request closes issue (#\d+)./, "该拉取请求将关闭议题 $1。"], // 死活不翻译
那个 (Close #267)

2024-08-18 05:47 UTC, maboloshi commented on locals.js
> +        [/This pull request closes issue (#\d+)./, "该拉取请求将关闭议题 $1。"], // 死活不翻译
我这边没有类似的显示

2024-08-18 05:49 UTC, wuyuncheng-26 commented on locals.js
> +        [/This pull request closes issue (#\d+)./, "该拉取请求将关闭议题 $1。"], // 死活不翻译
我这里也没用欸

2024-08-18 05:51 UTC, wuyuncheng-26 commented on locals.js
> +        [/This pull request closes issue (#\d+)./, "该拉取请求将关闭议题 $1。"], // 死活不翻译
哦哦哦，没事了
我找到了
![image](https://github.com/user-attachments/assets/7cd35c1f-85ca-4d08-a5d0-7624e40f40f6)

2024-08-18 06:03 UTC, maboloshi requested changes

2024-08-18 06:03 UTC, maboloshi commented on locals.js
> +        [/on (.+)/, "$1"], // 日期去除 on
提供一下截图

2024-08-18 06:03 UTC, maboloshi commented on locals.js
> +        [/This pull request closes issue (#\d+)./, "该拉取请求将关闭议题 $1。"], // 死活不翻译
好的 不翻译是没有定义翻译逻辑，后期看情况是否调整主函数

2024-08-18 06:03 UTC, maboloshi commented on locals.js
> +        [/on (.+)/, "$1"], // 日期去除 on
![image](https://github.com/user-attachments/assets/111960e4-b3fb-4650-aa8c-4edea21871bb)

2024-08-18 06:03 UTC, maboloshi commented on locals.js
> +        [/on (.+)/, "$1"], // 日期去除 on
请尝试调整公共正则第一条 如下修改
![image](https://github.com/user-attachments/assets/48a92e2c-3cb8-4d59-b5a8-07a1906551a5)

2024-08-18 06:30 UTC, merged

2024-08-18 13:55 UTC, TC999 commented on locals.js
> +        [/on (.+)/, "$1"], // 日期去除 on
这个无法去除

2024-08-18 14:03 UTC, maboloshi commented on locals.js
> +        [/on (.+)/, "$1"], // 日期去除 on
嗯 是的